/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IElAddLocation: typeof import('~icons/el/add-location')['default']
    IElLocation: typeof import('~icons/el/location')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAddMinus: typeof import('~icons/ep/add-minus')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IWdtAddLocation: typeof import('~icons/wdt/add-location')['default']
    IWdtLocation: typeof import('~icons/wdt/location')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
